version: 0.1.{build}
image:
- Visual Studio 2022
- Ubuntu
- macOS
platform:
- Win32
- x86
- x64
configuration: Release
matrix:
  exclude:
    - platform: Win32
      image: Ubuntu
    - platform: Win32
      image: macOS
    - platform: x86
      image: Visual Studio 2022
    - platform: x86
      image: macOS

build: off
build_script:
    - ps: |
        cmake --build build --config Release
        cmake --install build --config Release

artifacts:
    - path: bin
      name: HedgeLib

for:
-
  matrix:
    only:
      - image: Visual Studio 2022

  install:
    - ps: |
        mkdir "$env:APPVEYOR_BUILD_FOLDER\bin"
        .\Get-Dependencies.ps1 -Architecture $env:PLATFORM
        Write-Host "Downloading Vulkan SDK..." -ForegroundColor Green
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe" -OutFile "Dependencies\vulkan-sdk.exe"
        Write-Host "Installing Vulkan SDK..." -ForegroundColor Green
        .\Dependencies\vulkan-sdk.exe /S
        cmake -S . -B build "-DCMAKE_INSTALL_PREFIX=$env:APPVEYOR_BUILD_FOLDER\bin" -G "Visual Studio 17 2022" -A $env:PLATFORM
-
  matrix:
    only:
      - image: macOS

  install:
    - ps: |
        mkdir Dependencies; cd Dependencies
        git clone https://github.com/martinus/robin-hood-hashing.git
        cd robin-hood-hashing
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DRH_STANDALONE_PROJECT=OFF
        sudo cmake --build build --config Release
        sudo cmake --install build --config Release
        cd ../../
        brew install glm lz4 zlib glfw vulkan-headers molten-vk
        mkdir "$env:APPVEYOR_BUILD_FOLDER/bin"
        cmake -S . -B build "-DCMAKE_INSTALL_PREFIX=$env:APPVEYOR_BUILD_FOLDER/bin" -DCMAKE_BUILD_TYPE=Release
-
  matrix:
    only:
      - image: Ubuntu

  install:
    - sh: |
        if [ "$PLATFORM" == "x86" ]; then sudo apt-get update; sudo apt-get install -yq gcc-9-multilib g++-9-multilib; fi
        wget -qO - https://gist.githubusercontent.com/Radfordhound/6e6ce00535d14ae87d606ece93f1e336/raw/9796f644bdedaa174ed580a8aa6874ab82853170/install-lunarg-ubuntu-repo.sh | sh
    - ps: |
        mkdir Dependencies; cd Dependencies
        git clone https://github.com/martinus/robin-hood-hashing.git
        cd robin-hood-hashing
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DRH_STANDALONE_PROJECT=OFF
        cmake --build build --config Release
        sudo cmake --install build --config Release
        cd ../../
        sudo apt install -yq libglm-dev liblz4-dev zlib1g-dev libglfw3-dev vulkan-sdk
        mkdir "$env:APPVEYOR_BUILD_FOLDER/bin"
        cmake -S . -B build "-DCMAKE_INSTALL_PREFIX=$env:APPVEYOR_BUILD_FOLDER/bin" -DCMAKE_BUILD_TYPE=Release
