version: 0.1.{build}
image:
- Visual Studio 2019
- Ubuntu
- macOS
platform:
- Win32
- x86
- x64
configuration: Release
matrix:
  exclude:
    - platform: Win32
      image: Ubuntu
    - platform: Win32
      image: macOS
    - platform: x86
      image: Visual Studio 2019
    - platform: x86
      image: macOS

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - ps: |
        mkdir build
        cd build
        mkdir "$env:APPVEYOR_BUILD_FOLDER\bin"
        cmake "-DCMAKE_INSTALL_PREFIX=$env:APPVEYOR_BUILD_FOLDER\bin" -G "Visual Studio 16 2019" -A $env:PLATFORM ../
        echo "Cmake generation complete"
  build: off
  build_script:
    - ps: |
        echo "Starting msbuild for $env:APPVEYOR_BUILD_FOLDER\build\INSTALL.vcxproj"
        msbuild -v:minimal "$env:APPVEYOR_BUILD_FOLDER\build\INSTALL.vcxproj"
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER\License.txt" -Destination "$env:APPVEYOR_BUILD_FOLDER\bin\License.txt"
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER\Third-Party-Licenses.txt" -Destination "$env:APPVEYOR_BUILD_FOLDER\bin\Third-Party-Licenses.txt"
  artifacts:
    - path: bin
      name: HedgeLib
-
  matrix:
    only:
      - image: macos

  install:
    - ps: |
        brew install glm lz4 zlib
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../
  build: off
  build_script:
    - ps: |
        mkdir "$env:APPVEYOR_BUILD_FOLDER/bin"
        make "DESTDIR=$env:APPVEYOR_BUILD_FOLDER/bin" install
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER\License.txt" -Destination "$env:APPVEYOR_BUILD_FOLDER\bin\License.txt"
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER\Third-Party-Licenses.txt" -Destination "$env:APPVEYOR_BUILD_FOLDER\bin\Third-Party-Licenses.txt"
  artifacts:
    - path: bin
      name: HedgeLib
-
  matrix:
    only:
      - image: Ubuntu

  install:
    - sh: if [ "$PLATFORM" == "x86" ]; then sudo apt-get update; sudo apt-get install -yq gcc-9-multilib g++-9-multilib; fi
    - ps: |
        sudo apt install -yq libglm-dev liblz4-dev zlib1g-dev
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../
  build: off
  build_script:
    - ps: |
        mkdir "$env:APPVEYOR_BUILD_FOLDER/bin"
        make CPP=g++-9 CXX=g++-9 LD=g++-9 "DESTDIR=$env:APPVEYOR_BUILD_FOLDER/bin" install
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER\License.txt" -Destination "$env:APPVEYOR_BUILD_FOLDER\bin\License.txt"
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER\Third-Party-Licenses.txt" -Destination "$env:APPVEYOR_BUILD_FOLDER\bin\Third-Party-Licenses.txt"
  artifacts:
    - path: bin
      name: HedgeLib
