version: 0.1.{build}
image:
- Visual Studio 2019
- Ubuntu
- macOS
platform:
- Win32
- x86
- x64
configuration: Release
matrix:
  exclude:
    - platform: Win32
      image: Ubuntu
    - platform: Win32
      image: macOS
    - platform: x86
      image: Visual Studio 2019
    - platform: x86
      image: macOS

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - ps: |
        mkdir build
        cd build
        mkdir "$dir\bin"
        cmake "-DCMAKE_INSTALL_PREFIX=$dir\bin" -G "Visual Studio 16 2019" -A $env:PLATFORM ../
  build:
    project: build/INSTALL.vcxproj
    verbosity: minimal
  after_build:
    - ps: |
        Copy-Item "$dir\License.txt" -Destination "$dir\bin\License.txt"
        Copy-Item "$dir\Third-Party-Licenses.txt" -Destination "$dir\bin\Third-Party-Licenses.txt"
  artifacts:
    - path: bin
      name: HedgeLib
-
  matrix:
    only:
      - image: macos

  install:
    - ps: |
        brew install glm lz4 zlib
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../
  build: off
  build_script:
    - ps: |
        mkdir "$dir/bin"
        make "DESTDIR=$dir/bin" install
        Copy-Item "$dir\License.txt" -Destination "$dir\bin\License.txt"
        Copy-Item "$dir\Third-Party-Licenses.txt" -Destination "$dir\bin\Third-Party-Licenses.txt"
  artifacts:
    - path: bin
      name: HedgeLib
-
  matrix:
    only:
      - image: Ubuntu

  install:
    - sh: if [ "$PLATFORM" == "x86" ]; then sudo apt-get update; sudo apt-get install -yq gcc-9-multilib g++-9-multilib; fi
    - ps: |
        sudo apt install libglm-dev liblz4-dev zlib1g-dev
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../
  build: off
  build_script:
    - ps: |
        mkdir "$dir/bin"
        make CPP=g++-9 CXX=g++-9 LD=g++-9 "DESTDIR=$dir/bin" install
        Copy-Item "$dir\License.txt" -Destination "$dir\bin\License.txt"
        Copy-Item "$dir\Third-Party-Licenses.txt" -Destination "$dir\bin\Third-Party-Licenses.txt"
  artifacts:
    - path: bin
      name: HedgeLib
