version: 0.1.{build}
image:
- Visual Studio 2022
- Ubuntu
- macOS
platform:
- Win32
- x86
- x64
configuration: Release
matrix:
  exclude:
    - platform: Win32
      image: Ubuntu
    - platform: Win32
      image: macOS
    - platform: x86
      image: Visual Studio 2022
    - platform: x86
      image: macOS

build: off
build_script:
    - ps: |
        cmake --build build --target install --config Release
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER/License.txt" -Destination "$env:APPVEYOR_BUILD_FOLDER/bin/License.txt"
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER/Third-Party-Licenses.txt" -Destination "$env:APPVEYOR_BUILD_FOLDER/bin/Third-Party-Licenses.txt"

artifacts:
    - path: bin
      name: HedgeLib

for:
-
  matrix:
    only:
      - image: Visual Studio 2022

  install:
    - ps: |
        mkdir "$env:APPVEYOR_BUILD_FOLDER\bin"
        .\Get-Dependencies.ps1
        cmake -S . -B build "-DCMAKE_INSTALL_PREFIX=$env:APPVEYOR_BUILD_FOLDER\bin" -G "Visual Studio 16 2022" -A $env:PLATFORM
-
  matrix:
    only:
      - image: macOS

  install:
    - ps: |
        mkdir Dependencies
        cd Dependencies
        git clone https://github.com/martinus/robin-hood-hashing.git
        cd robin-hood-hashing
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        sudo cmake --build build --config Release
        sudo cmake --install build --config Release
        cd ../../
        brew install glm lz4 zlib
        mkdir "$env:APPVEYOR_BUILD_FOLDER/bin"
        cmake -S . -B build "-DCMAKE_INSTALL_PREFIX=$env:APPVEYOR_BUILD_FOLDER/bin" -DCMAKE_BUILD_TYPE=Release
-
  matrix:
    only:
      - image: Ubuntu

  install:
    - sh: if [ "$PLATFORM" == "x86" ]; then sudo apt-get update; sudo apt-get install -yq gcc-9-multilib g++-9-multilib; fi
    - ps: |
        mkdir Dependencies
        cd Dependencies
        git clone https://github.com/martinus/robin-hood-hashing.git
        cd robin-hood-hashing
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        sudo cmake --install build --config Release
        cd ../../
        sudo apt install -yq libglm-dev liblz4-dev zlib1g-dev
        mkdir "$env:APPVEYOR_BUILD_FOLDER/bin"
        cmake -S . -B build "-DCMAKE_INSTALL_PREFIX=$env:APPVEYOR_BUILD_FOLDER/bin" -DCMAKE_BUILD_TYPE=Release
